apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: christophersesugh/casbytes-content-dev
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: content-srv
spec:
  selector:
    app: content
  ports:
    - name: content
      protocol: TCP
      port: 3000
      targetPort: 3000
