apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: christophersesugh/casbytes-mailer-dev
          env:
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: database-url
            #       key: DATABASE_URL
            - name: RABBITMQ_URL
              value: "amqp://casbytes:sesugh@185@casbytes-rabbitmq"
              # valueFrom:
              #   secretKeyRef:
              #     name: rabbitmq-url
              #     key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-srv
spec:
  selector:
    app: mailer
  ports:
    - name: mailer
      protocol: TCP
      port: 3000
      targetPort: 3000
